pipeline {
    agent {
        label 'agent'
    }
    stages {
        stage('Example Stage') {
            steps {
                // Add your build steps here
                echo 'This job is running on the specified agent'
            }
        }
        
          stage('Example Stage1') {
            steps {
                // Add your build steps here
                echo 'This job is running on the specified agent done'
                }
        
        }
        
         stage('Example Stage2') {
            steps {
                // Add your build steps here
                echo 'This job is running on the specified agent done done'
                }
        
        }
    }
}

